[build]
command = "npm run build"
publish = "_site"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.thresholds]
accessibility = 1.0
best-practices = 1.0
performance = 1.0
seo = 1.0

[plugins.inputs]
output_path = "reports/lighthouse/index.html"
