[build]
command = "npm run build"
publish = "_site"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.thresholds]
accessibility = 0.9
best-practices = 0.9
performance = 1
seo = 1

[plugins.inputs]
output_path = "reports/lighthouse/index.html"
